<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractMedia
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property string $description
* @property string $url
* @property tinyInteger $media_type_id
* @property \App\Models\mediaType $mediaType
*/ 
abstract class AbstractMedia extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'url' => 'string',
        'media_type_id' => 'integer'
    ];
    
    public function mediaType()
    {
        return $this->belongsTo('\App\Models\mediaType', 'media_type_id', 'id');
    }
    
    public function groups()
    {
        return $this->belongsToMany('\App\Models\group', 'group_media', 'media_id', 'group_id');
    }
}
