<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractGroupMemberIndicatorOutro
* @package App\Models\AbstractModels
*
* @property integer $group_member_indicator_id
* @property string $answer
* @property \App\Models\GroupMember_Indicator $groupMemberIndicator
*/ 
abstract class AbstractGroupMemberIndicatorOutro extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'group_member_indicator_id';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'group_member_indicator_id' => 'integer',
        'answer' => 'string'
    ];
    
    public function groupMemberIndicator()
    {
        return $this->belongsTo('\App\Models\GroupMember_Indicator', 'group_member_indicator_id', 'id');
    }
}
