<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractIndicator
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property \Illuminate\Database\Eloquent\Collection $options
* @property \Illuminate\Database\Eloquent\Collection $userIndicators
* @property \Illuminate\Database\Eloquent\Collection $groupMemberIndicators
*/ 
abstract class AbstractIndicator extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];
    
    public function options()
    {
        return $this->hasMany('\App\Models\option', 'indicator_id', 'id');
    }
    
    public function userIndicators()
    {
        return $this->hasMany('\App\Models\User_Indicator', 'indicator_id', 'id');
    }
    
    public function groupMemberIndicators()
    {
        return $this->hasMany('\App\Models\GroupMember_Indicator', 'indicator_id', 'id');
    }
    
    public function groups()
    {
        return $this->belongsToMany('\App\Models\group', 'group_indicator', 'indicator_id', 'group_id');
    }
    
    public function apps()
    {
        return $this->belongsToMany('\App\Models\App', 'app_indicator', 'indicator_id', 'app_id');
    }
}
