<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractFile
* @package App\Models\AbstractModels
*
* @property smallInteger $id
* @property string $name
* @property string $url
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property tinyInteger $project_id
* @property tinyInteger $file_type_id
* @property tinyInteger $status_id
* @property \App\Models\project $project
* @property \App\Models\fileType $fileType
* @property \App\Models\status $status
*/ 
abstract class AbstractFile extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'url' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'project_id' => 'integer',
        'file_type_id' => 'integer',
        'status_id' => 'integer'
    ];
    
    public function project()
    {
        return $this->belongsTo('\App\Models\project', 'project_id', 'id');
    }
    
    public function fileType()
    {
        return $this->belongsTo('\App\Models\fileType', 'file_type_id', 'id');
    }
    
    public function status()
    {
        return $this->belongsTo('\App\Models\status', 'status_id', 'id');
    }
}
