<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractWithdraw
* @package App\Models\AbstractModels
*
* @property \Carbon\Carbon $left_at
* @property tinyInteger $withdraw_reason_id
* @property smallInteger $group_member_id
* @property \App\Models\withdrawReason $withdrawReason
* @property \App\Models\group_member $groupMember
*/ 
abstract class AbstractWithdraw extends Model
{
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'left_at' => 'datetime:Y-m-d',
        'withdraw_reason_id' => 'integer',
        'group_member_id' => 'integer'
    ];
    
    public function withdrawReason()
    {
        return $this->belongsTo('\App\Models\withdrawReason', 'withdraw_reason_id', 'id');
    }
    
    public function groupMember()
    {
        return $this->belongsTo('\App\Models\group_member', 'group_member_id', 'id');
    }
}
