<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractQuestionaire
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property string $default_question
* @property tinyInteger $default_interval
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractQuestionaire extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'default_question' => 'string',
        'default_interval' => 'integer',
        'updated_at' => 'datetime'
    ];
    
    public function groups()
    {
        return $this->belongsToMany('\App\Models\group', 'group_questionaire', 'questionaire_id', 'group_id')->withPivot('id');
    }
}
