<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractStatus
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property \Illuminate\Database\Eloquent\Collection $users
* @property \Illuminate\Database\Eloquent\Collection $projects
* @property \Illuminate\Database\Eloquent\Collection $groups
* @property \Illuminate\Database\Eloquent\Collection $files
*/ 
abstract class AbstractStatus extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'status';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];
    
    public function users()
    {
        return $this->hasMany('\App\Models\user', 'status_id', 'id');
    }
    
    public function projects()
    {
        return $this->hasMany('\App\Models\project', 'status_id', 'id');
    }
    
    public function groups()
    {
        return $this->hasMany('\App\Models\group', 'status_id', 'id');
    }
    
    public function files()
    {
        return $this->hasMany('\App\Models\file', 'status_id', 'id');
    }
}
