<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUserIndicator
* @package App\Models\AbstractModels
*
* @property integer $id
* @property integer $user_id
* @property tinyInteger $option_id
* @property tinyInteger $indicator_id
* @property \App\Models\user $user
* @property \App\Models\option $option
* @property \App\Models\indicator $indicator
* @property \App\Models\User_Indicator_Outro $userIndicatorOutros
*/ 
abstract class AbstractUserIndicator extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'option_id' => 'integer',
        'indicator_id' => 'integer'
    ];
    
    public function user()
    {
        return $this->belongsTo('\App\Models\user', 'user_id', 'id');
    }
    
    public function option()
    {
        return $this->belongsTo('\App\Models\option', 'option_id', 'id');
    }
    
    public function indicator()
    {
        return $this->belongsTo('\App\Models\indicator', 'indicator_id', 'id');
    }
    
    public function userIndicatorOutros()
    {
        return $this->hasOne('\App\Models\User_Indicator_Outro', 'user_indicator_id', 'id');
    }
}
