<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractWeekday
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property \Illuminate\Database\Eloquent\Collection $groups
* @property \Illuminate\Database\Eloquent\Collection $groupMembers
*/ 
abstract class AbstractWeekday extends Model
{
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'portuguese' => 'string'
    ];

    protected $fillable = [];
    
    public function groups()
    {
        return $this->hasMany('\App\Models\group', 'weekday_id', 'id');
    }
    
    public function groupMembers()
    {
        return $this->hasMany('\App\Models\group_member', 'weekday_id', 'id');
    }
}
