<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractOption
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property tinyInteger $indicator_id
* @property \App\Models\indicator $indicator
* @property \Illuminate\Database\Eloquent\Collection $userIndicators
* @property \Illuminate\Database\Eloquent\Collection $groupMemberIndicators
*/ 
abstract class AbstractOption extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'indicator_id' => 'integer'
    ];
    
    public function indicator()
    {
        return $this->belongsTo('\App\Models\indicator', 'indicator_id', 'id');
    }
    
    public function userIndicators()
    {
        return $this->hasMany('\App\Models\User_Indicator', 'option_id', 'id');
    }
    
    public function groupMemberIndicators()
    {
        return $this->hasMany('\App\Models\GroupMember_Indicator', 'option_id', 'id');
    }
}
