<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractApp
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property string $version
*/ 
abstract class AbstractApp extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'version' => 'string'
    ];
    
    public function indicators()
    {
        return $this->belongsToMany('\App\Models\indicator', 'app_indicator', 'app_id', 'indicator_id');
    }
}
