<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractFileType
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property \Illuminate\Database\Eloquent\Collection $files
*/ 
abstract class AbstractFileType extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];
    
    public function files()
    {
        return $this->hasMany('\App\Models\file', 'file_type_id', 'id');
    }
}
