<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractResponsibleAdult
* @package App\Models\AbstractModels
*
* @property string $fullname
* @property string $phone_number
* @property smallInteger $group_member_id
* @property \App\Models\group_member $groupMember
*/ 
abstract class AbstractResponsibleAdult extends Model
{
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'fullname' => 'string',
        'phone_number' => 'string',
        'group_member_id' => 'integer'
    ];
    
    public function groupMember()
    {
        return $this->belongsTo('\App\Models\group_member', 'group_member_id', 'id');
    }
}
