<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractQuestion
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property \Illuminate\Database\Eloquent\Collection $media
*/ 
abstract class AbstractQuestion extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'text' => 'string',
        'question_type_id' => 'integer',
        'tendency_id' => 'integer'
    ];
    
    public function type()
    {
        return $this->belongsTo('\App\Models\question_type', 'question_type_id', 'id');
    }

    public function options()
    {
        return $this->hasMany('\App\Models\media', 'media_type_id', 'id');
    }


}
