<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Relations\Pivot;

/**
* Class AbstractGroupQuestionaire
* @package App\Models\AbstractModels
*
* @property smallInteger $id
* @property tinyInteger $questionaire_id
* @property smallInteger $group_id
*/ 
abstract class AbstractGroupQuestionaire extends Pivot
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'questionaire_id' => 'integer',
        'group_id' => 'integer'
    ];
}
