<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractNonWorkingPeriod
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property \Carbon\Carbon $start_date
* @property \Carbon\Carbon $end_date
* @property tinyInteger $reason_id
* @property \App\Models\nonWorkingReason $reason
*/ 
abstract class AbstractNonWorkingPeriod extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'start_date' => 'datetime:Y-m-d',
        'end_date' => 'datetime:Y-m-d',
        'reason_id' => 'integer'
    ];
    
    public function reason()
    {
        return $this->belongsTo('\App\Models\nonWorkingReason', 'reason_id', 'id');
    }
    
    public function groups()
    {
        return $this->belongsToMany('\App\Models\group', 'group_non_working_period', 'non_working_period_id', 'group_id');
    }
}
