<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractWorkshop
* @package App\Models\AbstractModels
*
* @property smallInteger $id
* @property tinyInteger $workshop_num
* @property \Carbon\Carbon $date
* @property \Carbon\Carbon $time
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property smallInteger $group_id
* @property tinyInteger $wokshop_status_id
* @property \App\Models\group $group
* @property \App\Models\wokshopStatus $wokshopStatus
*/ 
abstract class AbstractWorkshop extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'workshop_num' => 'integer',
        'date' => 'datetime:Y-m-d',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'group_id' => 'integer',
        'wokshop_status_id' => 'integer'
    ];
    
    public function group()
    {
        return $this->belongsTo('\App\Models\group', 'group_id', 'id');
    }
    
    public function wokshopStatus()
    {
        return $this->belongsTo('\App\Models\wokshopStatus', 'wokshop_status_id', 'id');
    }
    
    public function groupMembers()
    {
        return $this->belongsToMany('\App\Models\group_member', 'group_member_workshop', 'workshop_id', 'group_member_id')->withPivot('id', 'attended_at', 'started_at', 'finished_at', 'total_seconds_interrupted');
    }
}
