<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Relations\Pivot;

/**
* Class AbstractGroupMemberWorkshop
* @package App\Models\AbstractModels
*
* @property smallInteger $id
* @property smallInteger $workshop_id
* @property smallInteger $group_member_id
* @property \Carbon\Carbon $attended_at
* @property \Carbon\Carbon $started_at
* @property \Carbon\Carbon $finished_at
* @property smallInteger $total_seconds_interrupted
*/ 
abstract class AbstractGroupMemberWorkshop extends Pivot
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'workshop_id' => 'integer',
        'group_member_id' => 'integer',
        'attended_at' => 'datetime:Y-m-d',
        'total_seconds_interrupted' => 'integer'
    ];
}
