<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUserIndicatorOutro
* @package App\Models\AbstractModels
*
* @property integer $user_indicator_id
* @property string $answer
* @property \App\Models\User_Indicator $userIndicators
*/ 
abstract class AbstractUserIndicatorOutro extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'user_indicator_id';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'user_indicator_id' => 'integer',
        'answer' => 'string'
    ];
    
    public function userIndicators()
    {
        return $this->belongsTo('\App\Models\User_Indicator', 'user_indicator_id', 'id');
    }
}
