<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractGroupMemberIndicator
* @package App\Models\AbstractModels
*
* @property integer $id
* @property smallInteger $group_member_id
* @property tinyInteger $indicator_id
* @property tinyInteger $option_id
* @property \App\Models\group_member $groupMember
* @property \App\Models\indicator $indicator
* @property \App\Models\option $option
* @property \App\Models\GroupMember_Indicator_Outro $groupMemberIndicatorOutros
*/ 
abstract class AbstractGroupMemberIndicator extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'group_member_id' => 'integer',
        'indicator_id' => 'integer',
        'option_id' => 'integer'
    ];
    
    public function groupMember()
    {
        return $this->belongsTo('\App\Models\group_member', 'group_member_id', 'id');
    }
    
    public function indicator()
    {
        return $this->belongsTo('\App\Models\indicator', 'indicator_id', 'id');
    }
    
    public function option()
    {
        return $this->belongsTo('\App\Models\option', 'option_id', 'id');
    }
    
    public function groupMemberIndicatorOutros()
    {
        return $this->hasOne('\App\Models\GroupMember_Indicator_Outro', 'group_member_indicator_id', 'id');
    }
}
