<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractMemberWorkshop
* @package App\Models\AbstractModels
*
* @property mediumInteger $id
* @property \Carbon\Carbon $inicio
* @property \Carbon\Carbon $fim
* @property boolean $interrupcao
* @property \Carbon\Carbon $created_at
* @property smallInteger $participante_grupo_id
*/ 
abstract class AbstractMemberWorkshop extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'interrupcao' => 'boolean',
        'created_at' => 'datetime',
        'participante_grupo_id' => 'integer'
    ];
}
