<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractLongQuestionaire
* @package App\Models\AbstractModels
*
* @property tinyInteger $id
* @property string $name
* @property tinyInteger $workshop_interval
*/ 
abstract class AbstractLongQuestionaire extends Model
{
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'workshop_interval' => 'integer'
    ];
}
